/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const DeploymentConfigInstanceType: core.serialization.Schema<
    serializers.DeploymentConfigInstanceType.Raw,
    Scrapybara.DeploymentConfigInstanceType
> = core.serialization.enum_(["ubuntu", "browser", "windows"]);

export declare namespace DeploymentConfigInstanceType {
    export type Raw = "ubuntu" | "browser" | "windows";
}
